### ISSUE TITLE
Cant use boolean node anymore

### ISSUE THREAD

**Issue by weareedt** [RobProductions/OpenGraphGUI#7]
When using the boolean node the checkbox will become a float.

**Comment by RobProductions** [comment]
Will take a look at this when I update Vectors, appreciate your patience and thanks for letting me know!

**Comment by RobProductions** [comment]
Hey @weareedt , apologies for the long delay but I've finally had some time to take a look at this now that I'm between projects. I discovered that Unity's confusing naming schemes caused me to pick [MaterialEditor.DefaultShaderProperty()](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/MaterialEditor.DefaultShaderProperty.html) as opposed to [MaterialEditor.ShaderProperty()](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/MaterialEditor.ShaderProperty.html) when rendering the "final" property to the Inspector. The former doesn't work with Booleans apparently, so I just swapped it out.

The issue is now fixed in the [latest release named 1.3.0](https://github.com/RobProductions/OpenGraphGUI/releases/tag/1.3.0) so feel free to check it out and thanks again for reporting this!
